### ISSUE TITLE
Flickering/Disappearing PEDs

### ISSUE THREAD

**Issue by Arkosee** [Motogege91/moto_greeneats#1]
**Describe the bug**
Players and NPC peds flicker/disappear when entering the main area

**Expected behavior**
To not flicker/disappear

**Screenshots**
https://youtu.be/Rv4hhv35ajo (Youtube Video)

**Desktop (please complete the following information):**
 - FiveM Artifacts: 8633
 - Game Build: 2944
 - Gabz tattooshop, clothingstore & barber (tattoo is closest, other 2 may not be within 1000)

**Comment by Motogege91** [comment]
Hi, yes is an occlusion problem. Usually maps share ymaps, and so we search
for the same ymap name into the map folder, and the tattoo map folder. It
should surely be a ymap named occ_something.ymap. Search for that file also
into gabz folder. If you enter discord and open a ticket we can coordinate
better, as I need to drop a fix to you.
https://linktr.ee/motogegeatelier

Il giorno dom 14 lug 2024 alle 00:51 Arkosee ***@***.***> ha
scritto:

**Comment by allyaminou** [comment]
So why not offer the solution here ? You want people to join discord wich I find that we are being force to do something we don't want. Keep your ''quality'' map. I'll find something better.

**Comment by Motogege91** [comment]
Hi, in order to keep the occlusions, you need to drop me the ymap of the other map you have that is conflicting……, I need to edit it to contain all the two maps having the conflict…… Is something you cannot do alone, and there is no prefixed solution. You should drop me the file…cause is some of YOUR maps to be problematic, not my repo. Keep your rude being and please don’t use this map. Also don’t use “we”, you are the only one having those kind of rude being and problems, so don’t normalize your lack of knowledge on how to install a map on a fivem server. Discord is for helping you hand by hand, good boy ;)

**Comment by allyaminou** [comment]
1st of all, you need to chill and don't take it so personal, I can flip the coin and say that now you are being rude for  calling me ''stupid'' in other words for not knowing that kind of information that certain maps are doing that due to the conflicts with other maps with the same name etc. I'm new to this so because I'm new that means I'm stupid ? Also not a ''boy'' but sure. Maybe you have the eyes escrowed. Thanks for the map and the awsome work you put in !
